/*
 * @author Fernando.
 * Proyecto FInal Algebra Lineal
 * 
 */
package calculadora;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class interfaz extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel modeloA = new DefaultTableModel();
    DefaultTableModel modeloB = new DefaultTableModel();
    DefaultTableModel modeloC = new DefaultTableModel();

    public interfaz() {
        initComponents();
        carga();
    }

    private void carga() {
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        modeloA.setColumnCount(0);
        modeloA.setRowCount(0);
        modeloB.setColumnCount(0);
        modeloB.setRowCount(0);
        tblA.setModel(modeloA);
        tblB.setModel(modeloB);
        modeloC.setColumnCount(0);
        modeloC.setRowCount(0);
        tblC.setModel(modeloC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMatrizA = new javax.swing.JPanel();
        txtAfila = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAcolumna = new javax.swing.JTextField();
        panelMatrizB = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtBfila = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtBcolumna = new javax.swing.JTextField();
        btnGen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblA = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblB = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblC = new javax.swing.JTable();
        panelResultados = new javax.swing.JPanel();
        btnMultiplicar = new javax.swing.JButton();
        btnResetear = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();
        btnMultiplicar1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbModoOscuro = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Final de Algebra Lineal");
        setResizable(false);

        panelMatrizA.setBackground(new java.awt.Color(255, 255, 255));
        panelMatrizA.setBorder(javax.swing.BorderFactory.createTitledBorder("Matriz A"));

        jLabel2.setText("# Filas");

        jLabel3.setText("# Columnas");

        javax.swing.GroupLayout panelMatrizALayout = new javax.swing.GroupLayout(panelMatrizA);
        panelMatrizA.setLayout(panelMatrizALayout);
        panelMatrizALayout.setHorizontalGroup(
            panelMatrizALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMatrizALayout.createSequentialGroup()
                .addGroup(panelMatrizALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMatrizALayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAfila, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMatrizALayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAcolumna, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelMatrizALayout.setVerticalGroup(
            panelMatrizALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMatrizALayout.createSequentialGroup()
                .addGroup(panelMatrizALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAfila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMatrizALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAcolumna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMatrizB.setBackground(new java.awt.Color(255, 255, 255));
        panelMatrizB.setBorder(javax.swing.BorderFactory.createTitledBorder("Matriz B"));

        jLabel11.setText("# Filas");

        jLabel12.setText("# Columnas");

        javax.swing.GroupLayout panelMatrizBLayout = new javax.swing.GroupLayout(panelMatrizB);
        panelMatrizB.setLayout(panelMatrizBLayout);
        panelMatrizBLayout.setHorizontalGroup(
            panelMatrizBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMatrizBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMatrizBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMatrizBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBcolumna, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBfila, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMatrizBLayout.setVerticalGroup(
            panelMatrizBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMatrizBLayout.createSequentialGroup()
                .addGroup(panelMatrizBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBfila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(panelMatrizBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtBcolumna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnGen.setText("Generar Matrices");
        btnGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenActionPerformed(evt);
            }
        });

        tblA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblA);

        tblB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblB);

        tblC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblC);

        panelResultados.setBackground(new java.awt.Color(255, 255, 255));
        panelResultados.setBorder(javax.swing.BorderFactory.createTitledBorder("Operaciones"));

        btnMultiplicar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnMultiplicar.setText("* C");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });

        btnResetear.setText("Resetear");
        btnResetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetearActionPerformed(evt);
            }
        });

        btnDividir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDividir.setText("/");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });

        btnRestar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRestar.setText("-");
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });

        btnSumar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSumar.setText("+");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });

        btnMultiplicar1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnMultiplicar1.setText("*  M");
        btnMultiplicar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelResultadosLayout = new javax.swing.GroupLayout(panelResultados);
        panelResultados.setLayout(panelResultadosLayout);
        panelResultadosLayout.setHorizontalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSumar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRestar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMultiplicar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMultiplicar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDividir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnResetear)
                .addGap(19, 19, 19))
        );
        panelResultadosLayout.setVerticalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResultadosLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSumar)
                    .addComponent(btnRestar)
                    .addComponent(btnMultiplicar)
                    .addComponent(btnDividir)
                    .addComponent(btnResetear)
                    .addComponent(btnMultiplicar1))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(102, 0, 0));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Calculadora de Matrices");

        cbModoOscuro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbModoOscuro.setForeground(new java.awt.Color(255, 255, 255));
        cbModoOscuro.setText("Modo Oscuro");
        cbModoOscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbModoOscuroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbModoOscuro)
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbModoOscuro))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelMatrizA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelMatrizB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnGen)
                            .addGap(134, 134, 134))))
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(panelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelMatrizB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMatrizA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnGen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenActionPerformed
        int Afila = Integer.parseInt(txtAfila.getText());
        int Acol = Integer.parseInt(txtAcolumna.getText());
        int Bfila = Integer.parseInt(txtBfila.getText());
        int Bcol = Integer.parseInt(txtBcolumna.getText());
        if (Acol != Bfila) {
            JOptionPane.showMessageDialog(null, "La columna de A debe ser igual a fila de B");
        } else {
            genA(Afila, Acol);
            genB(Bfila, Bcol);
            genC(Afila, Bcol);
        }
    }//GEN-LAST:event_btnGenActionPerformed

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        int r, i, j;
        double S = 0;
        double Afila = Double.parseDouble(txtAfila.getText());
        double Acol = Double.parseDouble(txtAcolumna.getText());
        double Bfila = Double.parseDouble(txtBfila.getText());
        double Bcol = Double.parseDouble(txtBcolumna.getText());
        for (i = 0; i < Afila; i++) {
            for (j = 0; j < Bcol; j++) {
                for (r = 0; r < Acol; r++) {
                    S = Double.parseDouble(modeloA.getValueAt(i, j).toString()) + Double.parseDouble(modeloB.getValueAt(i, j).toString());
                }
                modeloC.setValueAt(S + "", i, j);
                S = 0;
            }
        }

        /*for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                suma[i][j] = matrizA[i][j] + matrizB[i][j];
                System.out.print(suma[i][j] + "  ");
            }*/
    }//GEN-LAST:event_btnSumarActionPerformed

    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
        int r, i, j;
        double S = 0;
        double Afila = Integer.parseInt(txtAfila.getText());
        double Acol = Integer.parseInt(txtAcolumna.getText());
        double Bfila = Integer.parseInt(txtBfila.getText());
        double Bcol = Integer.parseInt(txtBcolumna.getText());
        for (i = 0; i < Afila; i++) {
            for (j = 0; j < Bcol; j++) {
                for (r = 0; r < Acol; r++) {
                    S = Double.parseDouble(modeloA.getValueAt(i, j).toString()) - Double.parseDouble(modeloB.getValueAt(i, j).toString());
                }
                modeloC.setValueAt(S + "", i, j);
                S = 0;
            }
        }
    }//GEN-LAST:event_btnRestarActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        int r, i, j;
        double S = 0;
        double Afila = Double.parseDouble(txtAfila.getText());
        double Acol = Double.parseDouble(txtAcolumna.getText());
        double Bfila = Double.parseDouble(txtBfila.getText());
        double Bcol = Double.parseDouble(txtBcolumna.getText());
        for (i = 0; i < Afila; i++) {
            for (j = 0; j < Bcol; j++) {
                for (r = 0; r < Acol; r++) {
                    S = Double.parseDouble(modeloA.getValueAt(i, j).toString()) / Double.parseDouble(modeloB.getValueAt(i, j).toString());
                }
                modeloC.setValueAt(((S* 100d)/100d) + "", i, j);
                S = 0;
                //System.out.print((double)Math.round(division[i][j] * 100d) / 100d);
            }
        }
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetearActionPerformed
        // TODO add your handling code here:
        txtAfila.setText("");
        txtAcolumna.setText("");
        txtBfila.setText("");
        txtBcolumna.setText("");
        ResetearMatrizA();
        ResetearMatrizB();
        ResetearMatrizC();
    }//GEN-LAST:event_btnResetearActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        int r, i, j;
        double S = 0;
        double Afila = Double.parseDouble(txtAfila.getText());
        double Acol = Double.parseDouble(txtAcolumna.getText());
        double Bfila = Double.parseDouble(txtBfila.getText());
        double Bcol = Double.parseDouble(txtBcolumna.getText());
        for (i = 0; i < Afila; i++) {
            for (j = 0; j < Bcol; j++) {
                for (r = 0; r < Acol; r++) {
                    S = Double.parseDouble(modeloA.getValueAt(i, j).toString()) * Double.parseDouble(modeloB.getValueAt(i, j).toString());
                }
                modeloC.setValueAt(S + "", i, j);
                S = 0;
            }
        }
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void cbModoOscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbModoOscuroActionPerformed
        // TODO add your handling code here:
        if (cbModoOscuro.isSelected()) {
            this.getContentPane().setBackground(Color.DARK_GRAY);
            panelMatrizA.setBackground(Color.LIGHT_GRAY);
            panelMatrizB.setBackground(Color.LIGHT_GRAY);
            panelResultados.setBackground(Color.LIGHT_GRAY);
        }else{
            this.getContentPane().setBackground(Color.WHITE);
            panelMatrizA.setBackground(Color.WHITE);
            panelMatrizB.setBackground(Color.WHITE);
            panelResultados.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_cbModoOscuroActionPerformed

    private void btnMultiplicar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicar1ActionPerformed
        // TODO add your handling code here:
        int r,i,j;
        double S=0;
        double Afila=Double.parseDouble(txtAfila.getText());
        double Acol=Double.parseDouble(txtAcolumna.getText());
        double Bfila=Double.parseDouble(txtBfila.getText());
        double Bcol=Double.parseDouble(txtBcolumna.getText());
        for(i=0;i<Afila;i++){
        for(j=0;j<Bcol;j++){
        for(r=0;r<Acol;r++){
            S=S+Double.parseDouble(modeloA.getValueAt(i, r).toString())*Double.parseDouble(modeloB.getValueAt(r, j).toString());
        }
        modeloC.setValueAt(S+"", i, j);
        S=0;
        }
        }
    }//GEN-LAST:event_btnMultiplicar1ActionPerformed

    private void ResetearMatrizA() {
        for (int i = 0; i < tblA.getRowCount(); i++) {
            for (int j = 0; j < tblA.getColumnCount(); j++) {
                tblA.setValueAt("", i, j);
            }
        }
    }
    
    private void ResetearMatrizB() {
        for (int i = 0; i < tblB.getRowCount(); i++) {
            for (int j = 0; j < tblB.getColumnCount(); j++) {
                tblB.setValueAt("", i, j);
            }
        }
    }
    
    private void ResetearMatrizC() {
        for (int i = 0; i < tblC.getRowCount(); i++) {
            for (int j = 0; j < tblC.getColumnCount(); j++) {
                tblC.setValueAt("", i, j);
            }
        }
    }

    private void genA(int fil, int col) {

        modeloA.setRowCount(fil);
        modeloA.setColumnCount(col);
        tblA.setModel(modeloA);
    }

    private void genB(int fil, int col) {
        modeloB.setRowCount(fil);
        modeloB.setColumnCount(col);
        tblB.setModel(modeloB);
    }

    private void genC(int fil, int col) {
        modeloC.setColumnCount(col);
        modeloC.setRowCount(fil);
        tblC.setModel(modeloC);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnGen;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnMultiplicar1;
    private javax.swing.JButton btnResetear;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSumar;
    private javax.swing.JCheckBox cbModoOscuro;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelMatrizA;
    private javax.swing.JPanel panelMatrizB;
    private javax.swing.JPanel panelResultados;
    private javax.swing.JTable tblA;
    private javax.swing.JTable tblB;
    private javax.swing.JTable tblC;
    private javax.swing.JTextField txtAcolumna;
    private javax.swing.JTextField txtAfila;
    private javax.swing.JTextField txtBcolumna;
    private javax.swing.JTextField txtBfila;
    // End of variables declaration//GEN-END:variables
}
